[package]
name = "rust-pr"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }